/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-03-15 09:28:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Responsive Navigation Bar</title>\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("/* Additional CSS for background images with hover */\r\n");
      out.write(".image-sections {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	/* Arrange sections with space between */\r\n");
      out.write("	margin-bottom: 20px; /* Add spacing between sections */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".image-section {\r\n");
      out.write("	flex: 1; /* Make sections flexible to take equal space */\r\n");
      out.write("	position: relative;\r\n");
      out.write("	height: 100vh; /* Cover the entire viewport height */\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	background-position: center;\r\n");
      out.write("	overflow: hidden; /* Hide overflowing content */\r\n");
      out.write("	border-radius: 10px; /* Add border radius for rounded corners */\r\n");
      out.write("	margin-bottom: 20px; /* Add margin between sections */\r\n");
      out.write("	padding: 20px; /* Add padding to create boxed appearance */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".overlay {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	background-color: rgba(0, 0, 0, 0.5);\r\n");
      out.write("	/* Semi-transparent black overlay */\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column; /* Arrange details from top to bottom */\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	opacity: 0;\r\n");
      out.write("	transition: opacity 0.3s; /* Smooth transition */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".overlay h2 {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	font-size: 24px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-bottom: 10px; /* Add spacing between title and content */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".overlay div {\r\n");
      out.write("	max-width: 300px;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	text-align: center; /* Center the content */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".overlay ol {\r\n");
      out.write("	padding-left: 0; /* Remove default padding */\r\n");
      out.write("	list-style: none; /* Remove default list style */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".overlay ol li {\r\n");
      out.write("	margin-bottom: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".image-section:hover .overlay {\r\n");
      out.write("	opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" /* Animation for sliding effect */\r\n");
      out.write("    @keyframes slideBackground {\r\n");
      out.write("      0% {\r\n");
      out.write("        background-position: 0 0;\r\n");
      out.write("      }\r\n");
      out.write("      100% {\r\n");
      out.write("        background-position: 100% 0;\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write(".image-section {\r\n");
      out.write("	animation: slideBackground 10s linear infinite;\r\n");
      out.write("	/* Adjust animation duration and timing as needed */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Additional CSS for horizontal navbar */\r\n");
      out.write(".navbar {\r\n");
      out.write("	background-color: #9370DB; /* Medium Purple */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-brand img {\r\n");
      out.write("	max-width: 50px; /* Adjust logo size */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Additional CSS for container */\r\n");
      out.write(".container-content {\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Additional CSS for buttons */\r\n");
      out.write(".btn {\r\n");
      out.write("	margin-top: 20px; /* Add spacing between buttons */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Additional CSS for navbar links */\r\n");
      out.write(".nav-link {\r\n");
      out.write("	color: #fff; /* White text color */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-link:hover {\r\n");
      out.write("	color: #f8f9fa; /* Lighter text color on hover */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Additional CSS for image section */\r\n");
      out.write(".image-sections {\r\n");
      out.write("	padding: 0 20px; /* Add padding to image sections container */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".image-section h2 {\r\n");
      out.write("	margin-bottom: 20px; /* Add spacing below section headings */\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-dark\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<a class=\"navbar-brand\" href=\"#\"> <img src=\"images/hostel.jpeg\"\r\n");
      out.write("				alt=\"Logo\">\r\n");
      out.write("			</a>\r\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("				data-target=\"#navbarNav\" aria-controls=\"navbarNav\"\r\n");
      out.write("				aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("			</button>\r\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("				<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("					<li class=\"nav-item active\"><a class=\"nav-link\" href=\"welcome_page.jsp\">Home</a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"nav-item active\"><a class=\"nav-link\"\r\n");
      out.write("						href=\"PreviousBookingServlet?username=");
      out.print(request.getParameter("username"));
      out.write("\">Previous Bookings</a></li>\r\n");
      out.write("					<li class=\"nav-item active\"><a class=\"nav-link\" href=\"#\">About\r\n");
      out.write("							Us</a></li>\r\n");
      out.write("							\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container-content\">\r\n");
      out.write("		<h1>Welcome to our Hostel Sathya!</h1>\r\n");
      out.write("		<p style=\"font-weight: bold; font-size: 18px; color: #555;\">Warden:\r\n");
      out.write("			Ratan sir</p>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Image sections container -->\r\n");
      out.write("	<div class=\"container-fluid image-sections\">\r\n");
      out.write("		<section class=\"image-section\"\r\n");
      out.write("			style=\"background-image: url('images/luxury.jpeg');\">\r\n");
      out.write("			<div class=\"overlay\">\r\n");
      out.write("\r\n");
      out.write("				<h2>Luxury Deluxe Room</h2>\r\n");
      out.write("				<h4 style=\"color: lime;\">Available Rooms:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${luxuryRooms}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("				<div>\r\n");
      out.write("					<ol>\r\n");
      out.write("						<li>Free Wi-Fi</li>\r\n");
      out.write("						<li>Smart TV</li>\r\n");
      out.write("						<li>Hot Water</li>\r\n");
      out.write("						<li>AC</li>\r\n");
      out.write("						<li>King Size Bed</li>\r\n");
      out.write("						<li>Only Two people for one Room</li>\r\n");
      out.write("					</ol>\r\n");
      out.write("				</div>\r\n");
      out.write("				<h2>Price: Rs.800/day</h2>\r\n");
      out.write("				");

				int price1 = 800;
				session.setAttribute("price1", price1);
				
      out.write("\r\n");
      out.write("				<a href=\"book.jsp?type=luxury\" class=\"btn btn-primary\">BOOK HERE</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("		<section class=\"image-section\"\r\n");
      out.write("			style=\"background-image: url('images/deluxe.jpeg');\">\r\n");
      out.write("			<div class=\"overlay\">\r\n");
      out.write("				<h2>Deluxe Room</h2>\r\n");
      out.write("				<h4 style=\"color: lime;\">Available Rooms:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${deluxeRooms}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("				<div>\r\n");
      out.write("					<ol>\r\n");
      out.write("						<li>Free Wi-Fi</li>\r\n");
      out.write("						<li>Smart TV</li>\r\n");
      out.write("						<li>Hot Water</li>\r\n");
      out.write("						<li>Iron Bed</li>\r\n");
      out.write("						<li>Only three people for one Room</li>\r\n");
      out.write("					</ol>\r\n");
      out.write("				</div>\r\n");
      out.write("				<h2>Price: Rs.500/day</h2>\r\n");
      out.write("				");

				int price2 = 500;
				session.setAttribute("price2", price2);
				
      out.write("\r\n");
      out.write("				<a href=\"book.jsp?type=deluxe\" class=\"btn btn-primary\">BOOK HERE</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("		<section class=\"image-section\"\r\n");
      out.write("			style=\"background-image: url('images/normal.jpeg');\">\r\n");
      out.write("			<div class=\"overlay\">\r\n");
      out.write("				<h2>Normal Rooms</h2>\r\n");
      out.write("				<h4 style=\"color: lime;\">Available Rooms:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${normalRooms}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("				<div>\r\n");
      out.write("					<ol>\r\n");
      out.write("						<li>Free Wi-Fi</li>\r\n");
      out.write("						<li>Normal rooms</li>\r\n");
      out.write("						<li>Only Five people for one Room</li>\r\n");
      out.write("					</ol>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<h2>Price: Rs.300/day</h2>\r\n");
      out.write("				");

				int price3 = 300;
				session.setAttribute("price3", price3);
				
      out.write("\r\n");
      out.write("				");

				String username = request.getParameter("username");
				request.setAttribute("username", username);
				session.setAttribute("username", username);
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<a href=\"book.jsp?type=normal\" class=\"btn btn-primary\">BOOK HERE</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Bootstrap JS and jQuery -->\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
